### ISSUE TITLE
Please update version

### ISSUE THREAD

**Issue by sunyuyangg555** [smanikandan14/ThinDownloadManager#10]
compile 'com.mani:thindownloadmanager:1.0.0' can not use 'addCustomHeader()' and 'setRetryPolicy()'.

**Comment by smanikandan14** [comment]
Yes. I am facing some issues in uploading to maven central. Please use the library as project dependency mean time.

**Comment by pawegio** [comment]
+1

**Comment by monpac** [comment]
Having the same problem, I'll use the project dependancy for now. Hope you can sort it out. Thanks!

**Comment by avluis** [comment]
Any updates as to when will maven be sorted?

**Comment by nicklasl** [comment]
+1

**Comment by vitorprado** [comment]
How about remove the gradle dependency part from read me until the new version is not published?
It's confuse to keep this snippet there and I think is not necessary to say the 1.0.0 is outdated in read me too.

**Comment by smanikandan14** [comment]
Hi All. I uploaded the aar file into jcenter. Now the latest version can be downloaded through 
```
    compile 'com.mani:ThinDownloadManager:1.1.0'
```
