### ISSUE TITLE
Support pause and restart? 

### ISSUE THREAD

**Issue by MarkMjw** [smanikandan14/ThinDownloadManager#11]
Should supporting pause or restart the download request?

**Comment by smanikandan14** [comment]
Its a good feature to have. But it requires quit a amount of work to track the partially downloaded file and bytes so far downloaded. I had went through the AOSP's DownloadManager code. It uses ContentProvider and some sql tables to track. This library was initially planned to be thin to download files ( reasonable sized files ) within the lifetime of app. So i haven't implemented Pause/Restart feature. Sorry about that.
