### ISSUE TITLE
Can't download Chinese name file

### ISSUE THREAD

**Issue by sunyuyangg555** [smanikandan14/ThinDownloadManager#12]
I Can't download Chinese name file. what should I do?

**Comment by smanikandan14** [comment]
Can you give me sample name ? I can fix it.

**Comment by sunyuyangg555** [comment]
like “ E100000_mmm_技术部.pdf ”， space is also not OK.

**Comment by smanikandan14** [comment]
You need to encode the file name and download URL with UTF_8 encoding. 
For example.
String downloadUrl = "http://www.test.com/resources/E100000_mmm_技术部.pdf"
File filesDir = getExternalFilesDir("");
        try {
            String encodedUrl = URLEncoder.encode(downloadUrl, "UTF_8");
           String destinationFileName = URLEncoder.encode("E100000_mmm_技术部.pdf", "URF_8");
           Uri downloadUri = Uri.parse(encodedUrl);
           Uri destinationUri = Uri.parse(filesDir+"/"+destinationFileName);
           ......... ( give it to download request).
        } catch(UnsupportedEncodingException e) {
            e.printStackTrace();
        }

Hope this helps.

**Comment by sunyuyangg555** [comment]
Thanks， now it's work for me .
