### ISSUE TITLE
Start again a cancelled request

### ISSUE THREAD

**Issue by mederic** [smanikandan14/ThinDownloadManager#13]
I add 3 requests to a download manager then I call cancelAll.
A sacond later, I retry to download the same urls with the same downloadManager and the same listener. 
I expect to start a real download but instead, listener goes to onDownloadFailed because of a cancelled request.

Is there a workaround for that?

**Comment by smanikandan14** [comment]
You need to create a new Download Request object and start download again.

**Comment by mederic** [comment]
It's already what I've done :).

Check this dummy use case:

https://gist.github.com/mederic/28f4f1d70a3f6f3d0f85

This attempt to start a download. When progress is upper than 10%, we cancel all download and start the same download with a new DownloadRequest.

Expectation: Infinite "Sucess!" in log.
What I have: Infinite "failed! Download cancelled" in log.

**Comment by smanikandan14** [comment]
The gist has cancelAll in 'onProgress' callback. So none of the download is getting completed and you are canceling it every time there is a progress. Thats why you see status "FAILED".   Let me know if new download can be run successfully after a failure.
