### ISSUE TITLE
Selecting Log Level

### ISSUE THREAD

**Issue by pawegio** [smanikandan14/ThinDownloadManager#14]
I am missing feature to select a log level for ThinDownloadManager or just ability to remove logs.

**Comment by squinney** [comment]
Agreed - log is pretty noisy

**Comment by wangzhengyi** [comment]
I create this PR for this Issue, link: https://github.com/smanikandan14/ThinDownloadManager/pull/89

**Comment by smanikandan14** [comment]
This is available in version `1.3.0`
