### ISSUE TITLE
Pause & resume downloads, handling OnPause and OnResume while a download is ongoing.

### ISSUE THREAD

**Issue by ayz4sci** [smanikandan14/ThinDownloadManager#15]
How do I pause all downloads and resume as needed and handle OnPause and OnResume while a download is ongoing.? 
Eg In your sample app, when the app is paused due to a phone call the download stops or rather the UI changes (progress, etc) is cancelled.

**Comment by lhalegria** [comment]
I have the same issue

**Comment by utfqvfhpyygy** [comment]
I have the same issue

**Comment by smanikandan14** [comment]
The download will continue to happen as long as the download is initiated and the app is not killed. When phone call arrives, download will not be stopped. When Activity resumes, its your duty to query for the downloadID and check if the download is finished to update the UI. And the library doesn't support pause/resume like in DownloadManager comes with Android. This library is mainly used for downloading files which are relatives short and if you are downloading huge file and expect pause/resume options you may need to use Android's DownloadManager.
