### ISSUE TITLE
comment error.

### ISSUE THREAD

**Issue by pop1030123** [smanikandan14/ThinDownloadManager#17]
Constant STATUS_NOT_FOUND‘s comments  is same as STATUS_FAILED .(in DownloadManager.java)
       /**
	 * Status when the download has failed.
	 */
	public final static int STATUS_FAILED = 1 << 5;

	/**
	 * Status when the download has failed.
	 */
	public final static int STATUS_NOT_FOUND = 1 << 6;

**Comment by smanikandan14** [comment]
Thanks. Updated.https://github.com/smanikandan14/ThinDownloadManager/commit/28d20cc7468b3182e83e23bf5c66019acacf6b06
