### ISSUE TITLE
Null pointer exception onDestroy()

### ISSUE THREAD

**Issue by krishansharma91** [smanikandan14/ThinDownloadManager#20]
This is what I am getting on onDestroy(), where I am releasing it.  
java.lang.NullPointerException: Null pointer exception during instruction 'monitor-enter v1'
            at com.thin.downloadmanager.DownloadRequestQueue.finish(DownloadRequestQueue.java:194)
            at com.thin.downloadmanager.DownloadRequest.finish(DownloadRequest.java:145)
            at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:84)

Any Ideas what I am doing wrong?

**Comment by smanikandan14** [comment]
How have you integrated the library ? Looks like you have old version of the library. Please use the library as module in your project.

**Comment by krishansharma91** [comment]
I included it as a gradle dependency.Thanks I will try adding whole module.

**Comment by krishansharma91** [comment]
Thanks, that solved my issue.

**Comment by vitorprado** [comment]
I had the same problem. 
I'm using the lib via gradle and when the download finish the app crash and show the same stacktrace.
Can I use the lib via gradle?
