### ISSUE TITLE
Rename file?

### ISSUE THREAD

**Issue by xbroak** [smanikandan14/ThinDownloadManager#21]
Is it possible to do so?

**Comment by smanikandan14** [comment]
What do you mean rename file ?

**Comment by xbroak** [comment]
As in, when the file downloads to the folder, rename to something else 'myfile.mp3' without of course doing it manually via files and the path

**Comment by smanikandan14** [comment]
When creating downloadRequest you can specify the file name as your wish.

```
downloadUri = Uri.parse(FILE2);
        destinationUri = Uri.parse(filesDir+"/test_photo2.jpg");  --> Change the name to as your wish here.
        final DownloadRequest downloadRequest2 = new DownloadRequest(downloadUri)
                .setDestinationURI(destinationUri).setPriority(DownloadRequest.Priority.LOW)
                .setDownloadListener(myDownloadStatusListener);
```

**Comment by xbroak** [comment]
I tried that, it crashed immediately with a null reference.

Additionally, just tested on a 5.1.0 device and downloads will not begin at all, crashes immediately

**Comment by xbroak** [comment]
Some more info on 5.1.0

in DownloadDispatcher.java, line 232
Reason: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference

**Comment by xbroak** [comment]
Oh! My mistake, it turns out the crashing is happening on any version that's in an emulator.. real device works fine. I've still no idea why though.

**Comment by xbroak** [comment]
Does TDM create the folder if it does not exist (Destination URI)?

**Comment by smanikandan14** [comment]
No. it doesn't try to create the file if the destination file doesn't exist.

**Comment by xbroak** [comment]
Every single thing i do, creating the folders first, setting a name on the destination, not setting one, it will just NOT download nor rename the file. No idea what is possibly the problem, 9 times out of 10 i get the nullpointer error from DownloadDispatcher

final Uri destinationUri = Uri.parse(con.getFilesDir() + "/Downloaded/" + "83967" + "/" + "83967");

Download completes, no errors, no file made.

**Comment by xbroak** [comment]
I also get this in the log too if that helps

08-07 19:10:45.429: D/ThinDownloadManager(10506): cleanupDestination() deleting /data/data/uk.co.lbc.podcasts/files/Downloaded/83967/83967

Is it making the file then deleting it immediately?

**Comment by smanikandan14** [comment]
Would you mind sharing the download url. I can try locally and let you know what could be the issue ? (if it helps to solve the issue at your end )
