### ISSUE TITLE
Progress > 100

### ISSUE THREAD

**Issue by NorbertSzydlowski** [smanikandan14/ThinDownloadManager#22]
I have got progress 200 and more. v 1.0.0

**Comment by smanikandan14** [comment]
Sorry, the gradle dependency is out of date. 'compile 'com.mani:thindownloadmanager:1.0.0'. 
Please include the library as a project dependency in your project. It should solve your issue.

**Comment by NorbertSzydlowski** [comment]
I have got the same issue with project dependency

**Comment by smanikandan14** [comment]
Would you share the url for the file. ? I can check at my end. I tried downloading a '.gz' file. It is working fine.

**Comment by smanikandan14** [comment]
Closing this issue. If you still face the issue. Reopen with url which i can try for reproducing this issue.
