### ISSUE TITLE
why should new DownloadRequestQueue() every time

### ISSUE THREAD

**Issue by xiaomeixw** [smanikandan14/ThinDownloadManager#24]
only new DownloadRequestQueue() one time in Application ....

**Comment by smanikandan14** [comment]
What do you mean every time ?? 
```
/** Download request queue takes care of handling the request based on priority. */
    private DownloadRequestQueue mRequestQueue;

    /**
    * Default constructor
    */
    public ThinDownloadManager() {
        mRequestQueue = new DownloadRequestQueue();
        mRequestQueue.start();
    }

    /** Constructor taking MAX THREAD POOL SIZE  Allows maximum of 4 threads.
    * Any number higher than four or less than one wont be respected.
    **/
    public ThinDownloadManager(int threadPoolSize) {
        mRequestQueue = new DownloadRequestQueue(threadPoolSize);
        mRequestQueue.start();
    }
```

The request queue instance is created only once per ThindownloadManager instance. 

Its upto you to manage the 'ThindownloadManager' instance across your application. Its life cycle is decided by you. If you need a single instance across your application, you can create a singleton instance in your Application class and provide a static method to supply ThindownloadManager instance.

**Comment by xiaomeixw** [comment]
Ok,I know what your mean,I created 'ThinDownloadManager' in every activity ,so i was  mistake 'ThinDownloadManager'  for need create every time。So I will  manage the 'ThindownloadManager' in my application....Thanks for your library，it's so perfect base on volley framework thought ...

**Comment by xiaomeixw** [comment]
@smanikandan14  you can close the issue....Thanks...
