### ISSUE TITLE
Reason to limit threadPoolSize to 4

### ISSUE THREAD

**Issue by jzafrilla** [smanikandan14/ThinDownloadManager#26]
Hi, what is the reason to limit threadPoolSize to 4? I have to download over 30 files. 
Thanks in advance

**Comment by smanikandan14** [comment]
The ideal solution is to check for available processors and determine the thread count. I think i should update the library to check for available processors. Will update shortly.

I found this link covering the solution how to find the maximum reasonable thread pool size based on number of available processors.
http://www.scriptscoop.com/t/568ef812c761/java-how-to-choose-size-of-thread-pool-on-android.html

**Comment by smanikandan14** [comment]
Fixed this issue. Now the number of threads is determined based on the availability of number of processors at the runt time. Closing this issue. Check version `1.2.0`
