### ISSUE TITLE
Does it deletes the file itself sometime on low download speed?

### ISSUE THREAD

**Issue by DevendraSingh91** [smanikandan14/ThinDownloadManager#27]
I am facing this issue since 7days continually. and it seems when the data/file isn't downloaded properly or broken while downloading, it deletes the file, and sometime the Gallery shows a broken thumbnail. my downloading code snippet is 

                           holder.DownloadImage.setOnClickListener(new View.OnClickListener() {
                                  @Override
                               public void onClick(View view) {
                                    String  imgfilename="fdfdfdf.jpg"
                                      String SERVERURL= "http/myserver/uploads/";
                                      Uri downloadUri = Uri.parse(SERVERURL+ imgfilename);
                                     Uri destinationUri = Uri.parse(folder + "/" + imgfilename);
                                   final DownloadRequest downloadRequest = new DownloadRequest(downloadUri)
                                .setDestinationURI(destinationUri).setPriority(DownloadRequest.Priority.HIGH)
                                .setDownloadListener(new DownloadStatusListener() {
                                    @Override
                                    public void onDownloadComplete(int i) {

                                        String sdFolder= Environment.getExternalStorageDirectory() + "/MYFOLDER/" + imgfilename;
                                     
                                        BitmapFactory.Options options = new BitmapFactory.Options();
                                        options.inSampleSize = 99;
                                        Bitmap bmThumbnail = BitmapFactory.decodeFile(audioPath);
                                        holder.imageView.setImageBitmap(bmThumbnail);
                                 
                                    @Override
                                    public void onDownloadFailed(int i, int errorCode, String errorMessage) {
                                       
                                    }

                                    @Override
                                    public void onProgress(int i, long l, int i2) {
                                       

                                    }
                                });

                        if (downloadManager.query(downloadId1) == DownloadManager.STATUS_NOT_FOUND) {
                            downloadId1 = downloadManager.add(downloadRequest);
                        }
                       

                    }
                });

**Comment by hendrawd** [comment]
Since it's based on Volley, you can set the default retry policy to take longer timeout. So it can download even on slow internet speed.

Refer to the method below :
/**
     * Constructs a new retry policy.
     * @param initialTimeoutMs The initial timeout for the policy.
     * @param maxNumRetries The maximum number of retries.
     * @param backoffMultiplier Backoff multiplier for the policy.
     */
public DefaultRetryPolicy(int initialTimeoutMs, int maxNumRetries, float backoffMultiplier)

So, you can use something like this to the download request
DownloadRequest downloadRequest = new DownloadRequest(downloadUri)
            .setRetryPolicy(new DefaultRetryPolicy(150000, 0, 0))//150 secs timeout
            .any other parameter you want to set

**Comment by DevendraSingh91** [comment]
@hendrawd ok i will try retry policy.
