### ISSUE TITLE
Setting destination as a folder in external or internal storage 

### ISSUE THREAD

**Issue by bhuvneshvarma** [smanikandan14/ThinDownloadManager#28]
Can i set the path of destnation as a folder in external or internal storage instead of cache directory?

**Comment by smanikandan14** [comment]
Yes absolutely. But you might end up adding the permission on your manifest file. The library's main purpose is to avoid the permission if you are serious about it. Also you can use app's private directories which doesn't require permissions from android 4.4

Have a look at here.
http://developer.android.com/guide/topics/data/data-storage.html#filesExternal

**Comment by bhuvneshvarma** [comment]
I can see it has feature of cancelling a download..but can i delete already downloaded file with this library?
