### ISSUE TITLE
Error:(15, 32) error: package com.thin.downloadmanager does not exist

### ISSUE THREAD

**Issue by kaupov** [smanikandan14/ThinDownloadManager#30]
I have tried many ways to use .jar file in Android Studio 1.4 but it always end up with following error when using:

`import com.thin.downloadmanager.DownloadRequest;`

`Error:(15, 32) error: package com.thin.downloadmanager does not exist`

**Comment by smanikandan14** [comment]
Please try now. I have updated the jar file.

**Comment by smanikandan14** [comment]
Please use this in your build.gradle file and use jcenter for repositories.
```
compile 'com.mani:ThinDownloadManager:1.1.0'
```
