### ISSUE TITLE
Is #release() necessary?

### ISSUE THREAD

**Issue by DVassilev** [smanikandan14/ThinDownloadManager#32]
Hi,

What happens if I don't release the download manager? If it's necessary what is the best way to keep one download manager across the entire app that I can use from multiple activities and intent services which may finish prior to the download completing.

Thanks,
Daniel

**Comment by mradlmaier** [comment]
Hi,
I have the same question.

Thanks

**Comment by hendrawd** [comment]
After diving to the code, i have a conclusion that release is only needed when you need to cancel all the pending and running requests. If you need to let the download still running in the background, you don't need to call release.

For keeping the download manager to be available to all of your activities, you need to make the download manager declared to the application scope and can be requested from there. Or you can make a singleton of it.

CMIIW

**Comment by smanikandan14** [comment]
@hendrawd Thanks for stepping in. You got all the points covered. Closing this issue.
