### ISSUE TITLE
Resume download after closing the app !

### ISSUE THREAD

**Issue by daniaDlbani** [smanikandan14/ThinDownloadManager#37]
thanks for this library, I am trying to use it in order to download big files in range of ( 100 M to 400 )
I read the readMe file but it seems there is no way to resume download manually !
in case of connection problems or in case of exit the app
would you please suggest any solution to this issue?

**Comment by smanikandan14** [comment]
Sorry, this library is not intended for downloading large files. Yes, pause/resume functionality is not present in this library. You may need to use Android's DownloadManager and use permission download without user notification.

**Comment by smanikandan14** [comment]
Closing this issue.
