### ISSUE TITLE
Blocked ui thread when try to use notification's setProgress

### ISSUE THREAD

**Issue by marinat** [smanikandan14/ThinDownloadManager#38]
When I try use notification builder with setProgress in 
@Override
        public void onProgress(int id, long totalBytes, long downloadedBytes, int progress) {
I got blocked ui, can't scroll.
How to use notifications with this library?

**Comment by smanikandan14** [comment]
The onProgress is called on the main thread. And it is your responsibility to avoid doing heavy operations inside onProgress method. Please check your onProgress method. Or share your onProgress method code here.

**Comment by marinat** [comment]
In onCreate of MainActivity:

    mNotifyManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
    mBuilder = new NotificationCompat.Builder(MainActivity.this);
    mBuilder.setContentTitle("Picture Download")
            .setContentText("Download in progress")
            .setSmallIcon(android.R.drawable.arrow_down_float);

onProgress method:

    @Override
    public void onProgress(int id, long totalBytes, long downloadedBytes, int progress) {

        System.out.println("######## onProgress ###### " + id + " : " + totalBytes + " : " + downloadedBytes + " : " + progress);
        if (id == downloadId1) {
            mProgress1Txt.setText("Download1 id: " + id + ", " + progress + "%" + "  " + getBytesDownloaded(progress, totalBytes));
            mProgress1.setProgress(progress);
            mBuilder.setProgress(100, msg.what, false);
            // Displays the progress bar for the first time.
            Notification notif =mBuilder.build();
            notif.flags = Notification.FLAG_ONGOING_EVENT;
            mNotifyManager.notify(id, notif);                
        }
    ...

I thought, that mCallBackExecutor in DownloadRequestQueue class execute onProgress method in separate runnable, not in main thread. 

Ok, I tried change method postProgressUpdate in CallBackDelivery - subclass of DownloadRequestQueue like this:

		public void postProgressUpdate(final DownloadRequest request, final long totalBytes, final long downloadedBytes, final int progress) {
			Thread t = new Thread(new Runnable() {
				public void run() {
					request.getDownloadListener().onProgress(request.getDownloadId(), totalBytes, downloadedBytes, progress);
				}
			});
			t.start();
		}

And got no effect, I still get freezes. 

Could you add download with notifications?

**Comment by smanikandan14** [comment]
1. The CallBackDelivery is created with handler created from mainLopper. So the progress callback is given to you on main thread. Otherwise you cannot access UI elements in this callback. 

```
public DownloadRequestQueue() {
		mDownloadDispatchers = new DownloadDispatcher[DEFAULT_DOWNLOAD_THREAD_POOL_SIZE];
		mDelivery = new CallBackDelivery(new Handler(Looper.getMainLooper()));
	}
```
2. Don't create a new thread everytime to post a progress update which is wrong. 

3. Just comment the lines one by one in onProgress method and see which is causing freezing. 

The library purpose is to avoid using "DOWNLOAD_WITHOUT_NOTIFICATION" permission in your manifest. And your purpose is to show notification to users. You can very well use Android provided DownloadManager.

**Comment by marinat** [comment]
The problem is that Android DownloadManager don't download files of authorized dropbox user, every time I get 1008 error - download canceled. That's why I search alternative. 

mNotifyManager.notify(id, notif); - this string causing freezing. So, you say that there is no simple method to implement notifications with progressbar in your library?

**Comment by smanikandan14** [comment]
The library will not provide notifications & progress bar. It is the integrators choice to implement the progress bar or notifications in the call back. You need to find why NotifyManager.notify is causing freeze.

**Comment by Myerden** [comment]
use this method, I hope this fix your issue
[https://stackoverflow.com/a/17345996/4133449](https://stackoverflow.com/a/17345996/4133449)
