### ISSUE TITLE
how can i get the downloaded data before it saves on storage?

### ISSUE THREAD

**Issue by DevendraSingh91** [smanikandan14/ThinDownloadManager#40]
i implemented this very well, but i need to do some operation on the data(say image, and i want to fix its ratio,resolution before it saves the file) so i need the data before the library save the file.
plus what if i use this library for wide use(i.e.whatsapp, what it does when i do download more than 5 files on same time) and i have the recyclerview. what process is better and flexible to use this library like whatsapp?

**Comment by smanikandan14** [comment]
The raw data is not available to you until the download is fully completed. When you receive `onDownloadComplete` callback, you can access the file and perform your transformations ( for an image)and then save it back then update the UI.  

You can use this library along with recycler view to initiate multiple downloads and update the progress of download.
