### ISSUE TITLE
Provide DownloadRequest Object instead of the id

### ISSUE THREAD

**Issue by harinair** [smanikandan14/ThinDownloadManager#41]
When a complex application uses the ThinDownloadManager, it needs access to the download request context. Currently I can get the request context by saving the request context within my application essentially by keeping a HashMap of the download manager's request id to my download context. It is much easier for the client applications if
#1  the DownloadRequest had a downloadContext or clientContext object supplied by the client so that client does not need to maintain a HashMap.
#2 the listener object provided the DownloadRequest instead of the download id thus client will have everything it needs to identify the download in progress.

What do you think?

**Comment by naushad-madakiya** [comment]
+1

**Comment by smanikandan14** [comment]
@harinair Thanks for ideas. I will see how to go about this in implementation.

**Comment by harinair** [comment]
@smanikandan14 
Pull request submitted to fix this issue. Please merge the pull request if you approve of this change.

**Comment by smanikandan14** [comment]
Merged the PR.
