### ISSUE TITLE
can't know size of download, giving up on android 5

### ISSUE THREAD

**Issue by josmanperez** [smanikandan14/ThinDownloadManager#42]
Hi! I've been using the library with no problem at all until now, some users told me about they cannot update their feeds after updating to android 5, I've checked why and it's because of a missing header, more concretely, the content-length header, the thing is that this is just a necessary for android 5 devices, for pre lollipop everything works as expected and the download performs normally...

Do you have any idea why? and how to solve?

I have no control over the server side :(

**Comment by smanikandan14** [comment]
The "content-length" header is used primarily to identify the total size of the file ahead and that can be used to calculate the progress and given as callback for you to update the UI. Though this information is not a mandatory, i can allow the download to progress but you cannot expect progress in the callback in such cases.  Does your UI also indicates progress of download to user ?

**Comment by josmanperez** [comment]
Hi, thanks for anserwing, I do not provide a progress bar. The logic of the app is that in the onCreate method I have an asynctask that parses a json object to populate de data, this json is either on the assets folder or on the sd as a file saved in the device, then within the oncreate I made a donwload request just to download this json from a server and storage in a file and update the adapter. 

Until now it just work flawless, but now I realize out that everytime that you run the app on android 5 (yesterday I tested it in API 19 and also didn't work) after you set the donwload request you get the onDownloadFailed with error code 1006 and message "can't know the size of download, giving up) the strange thing is that on pre android 4.4.2 devices works perfect, no problem at all..

I've made a local copy of the server and added the content-length header by myself with the length of the json array and now it works on android 4.4.4 and beyond.. but I have no control over the production server.

Any idea why? and how to solve it?

**Comment by smanikandan14** [comment]
Fixed the issue. Use 1.2.0 version and let me know if it fixes you issue. I removed the strict check on availability of "Content-Length" header.

**Comment by josmanperez** [comment]
Hi! thanks for the answers!, 

Yesterday I made a copy of the library in my project for debug purposes, I found out that when you run the app on android 4.1 against the same server in the getContentLength method it retrieves the content length even though there was no explicit content length header, but when you do it on 4.2 or above it returns null so it puts a  "-1" and there was no chunked transfer encoding so it returns the error mention on the topic.. but finally I made a request for accessing the server and added the content-length along with the content-type header manually on those json get request and now works perfect, the weird thing is that if you remove the content-length header but leave the content-type header (with application/json) it now works too (before was the default content type header with text/html) I'll use the 1.2.0 version but I just want to tell you this

Thank you so much for answering me.

**Comment by smanikandan14** [comment]
Thanks for the sharing the analysis. Hope 1.2.0 fixes it.
