### ISSUE TITLE
cleanupDestination? Files getting deleted after download?

### ISSUE THREAD

**Issue by VeeruPV** [smanikandan14/ThinDownloadManager#50]
Hi there, Is this an intended behavior, Log out put shows  

cleanupDestination() deleting /data/data/hds.comcrave.hdsapp/app_filesdir/temp.pdf

I will need to use the downloaded file. This is my code

String file= getActivity().getDir("filesdir", Context.MODE_PRIVATE) + "/temp.pdf";
            final Uri downloadUri=Uri.parse(resourceListsFromServer.get(position).getUrl());
            Uri destinationUri=Uri.parse(file);
            dm=new ThinDownloadManager();

            final DownloadRequest downloadRequest = new DownloadRequest(downloadUri)
                    .setDestinationURI(destinationUri).setPriority(DownloadRequest.Priority.HIGH)
                    .setDownloadListener(new DownloadStatusListener() {
                        @Override
                        public void onDownloadComplete(int id) {
                            Utils.hideView(rlProgress, 200);
                            System.out.println("Download completed " + downloadUri);
                            ((Home)getActivity()).displayView(100);
                        }

                        @Override
                        public void onDownloadFailed(int id, int errorCode, String errorMessage) {
                            Utils.hideView(rlProgress, 200);
                            ShowdownloadError("Unable to download file at  " + errorMessage + "\r\n" + downloadUri);
                        }

                        @Override
                        public void onProgress(int id, long totalBytes, long downlaodedBytes, int progress) {

                        }
                    });
            Utils.showView(rlProgress, 200);

            int downloadId = dm.add(downloadRequest);
        } catch (Exception e) {
            e.printStackTrace();
            showFeedError("Failed with exception  \r\n"+e.getMessage());
        }finally{

        }

**Comment by edwardaa** [comment]
No, it's a bug, see the PR https://github.com/smanikandan14/ThinDownloadManager/pull/53

**Comment by smanikandan14** [comment]
@edwardaa  There is not bug here. The design i implemented is, when a download request is initiated
and destinationURI is provided, if file exists already with same name in the destination path, it deletes that file before initiating the request. So this is not a bug.

**Comment by edwardaa** [comment]
Ooooh, my bad, It's **NOT** a bug :)

**Comment by VikasPawar2112** [comment]
I want to download duplicate picture .
I used to same url to download picture and i am saved the those  picture as picture id.
So, they don't save into gallery. 
It show D/ThinDownloadManager: cleanupDestination() deleting /storage/emulated/0/Pictures/ShareApp/Pic74402848.jpg
So, it's possible to download duplicate pictures.

Here is my code:
public void download(List<Picture> pictureList) {
        this.pictureList = pictureList;
        Random random = new Random();
        for (Picture picture : pictureList) {
            RetryPolicy retryPolicy = new DefaultRetryPolicy();
            Uri downloadUri = Uri.parse(picture.getPicUrl());
            DownloadPictures.downloadIssue("Before Downloaded Picture Name" + picture.getPicUrl());
            String fileName = "Pic" + picture.getPicId()/*System.currentTimeMillis() + random.nextInt()*/ + ".jpg";
            Uri destinationUri = Uri.parse(shareAppFile + "/" + fileName);
            DownloadRequest downloadRequest1 = new DownloadRequest(downloadUri)
                    .setDestinationURI(destinationUri).setPriority(DownloadRequest.Priority.LOW)
                    .setRetryPolicy(retryPolicy)
                    .setDownloadContext(picture.getPicId())
                    .setStatusListener(downloadStatusListenerV1);
            downloadRequests.add(downloadManager.add(downloadRequest1));
        }
    }
