### ISSUE TITLE
1004 Error 

### ISSUE THREAD

**Issue by TapanM** [smanikandan14/ThinDownloadManager#62]
I am trying to download file using 1.2.4 version. Sometimes it is giving Error Message: IOException: Failed reading response. Error Code is 1004. Can you give me some tips why is it coming?

**Comment by PrimeKang** [comment]
This occurs when there is an exception reading from the network connection stream. I suspect you are disconnecting from WiFi during the download.

**Comment by smanikandan14** [comment]
@TapanM Let me know if this issue persists for you.

**Comment by willcodes** [comment]
Anyone ever figure this one out? I am experiencing this error but there are no wifi or connection errors.

**Comment by mouness2020** [comment]
Hello,,
Many users complains from this error 
i don't know why?
anyone have explain for this
i attached print screen from google analytic 
http://prntscr.com/fx5po3
