### ISSUE TITLE
Timeout and retry 

### ISSUE THREAD

**Issue by diabloo** [smanikandan14/ThinDownloadManager#7]
Hi ,
is there a way to set a time out and To retry Download if failed ?

**Comment by smanikandan14** [comment]
No. The support is not there right now. But i will add it. Think it is useful.

**Comment by smanikandan14** [comment]
@diabloo I added the support for setting time out and retry policy for download request. Please try.

**Comment by crysan** [comment]
+1

**Comment by smanikandan14** [comment]
@crysan sorry i am facing some 401 issue in updating to sonar. You may need to use the project as library dependency in your project.

**Comment by crysan** [comment]
Ok

**Comment by smanikandan14** [comment]
The retrypolicy is mostly inspired from Volley library. And most of thindownload manager design is inspired from Volley.I suggest you to go through it.

**Comment by smanikandan14** [comment]
Closing as the support is added.
