### ISSUE TITLE
notify after all download has finished.

### ISSUE THREAD

**Issue by MrThiago** [smanikandan14/ThinDownloadManager#77]
Is there a way to notify the user when all the download has finished after press Start All ?
thanks

**Comment by erginduran** [comment]
there is already a lisstener in lbirary. void onDownloadComplete (int id); you can check your all downloads in this method and if done,notify it.

**Comment by smanikandan14** [comment]
Thanks @erginduran. @MrThiago Thats the way to achieve what you wanted. You can keep a track of list of downloads you initiated and check if everything is completed when you receive `onDownloadComplete` method.
