### ISSUE TITLE
Pausing a download

### ISSUE THREAD

**Issue by azaabudeen** [smanikandan14/ThinDownloadManager#79]
Is there any way i can pause a download?

**Comment by wangzhengyi** [comment]
Only cancel, there is no pause and resume function. I hope someone can develop this function for ThinDownloadManager.

**Comment by praveen2gemini** [comment]
@azaabudeen @wangzhengyi I have implemented Resumable download feature. But my pull request pending with Review. once review done and merged. You will get the resumable feature.
Here It is my PR:
https://github.com/smanikandan14/ThinDownloadManager/pull/110

**Comment by faisalwahabicflix** [comment]
@praveen2gemini  can you please let me know how can we resume our previous paused downloads.

**Comment by praveen2gemini** [comment]
@faisalwahabicflix there is a method called `pause()` which would pause the download. to enable this you should set `.setDownloadResumable(true) // It enables resume download feature` with `DownloadRequest`. So It will not delete the downloaded file until it gets completed. There is no method to resume, so you can call usual way start the download. It would check internally `DownloadRequest` has resume feature or not, if It has, It will check file content length and downloaded length. then it will resume the download.

**Comment by farhad-kargaran** [comment]
Hi, I can not find .setDownloadResumable(true) in downloadRequest .set params
it is available in 1.3.0 version?

**Comment by praveen2gemini** [comment]
@farhad-kargaran  please check the version **## 1.4.0**

**Comment by praveen2gemini** [comment]
@smanikandan14  Please close this issue. I hope, they got the solution.

**Comment by farhad-kargaran** [comment]
@pravern2gemini thank you very much. 1.4.0 is great

**Comment by praveen2gemini** [comment]
@smanikandan14 Please update the version 1.4.0 readMe file. Stil it is showing 1.3.0. Thanks.
```
dependencies {
    compile 'com.mani:ThinDownloadManager:1.3.0'
}
```
