### ISSUE TITLE
Perform no flow

### ISSUE THREAD

**Issue by crysan** [smanikandan14/ThinDownloadManager#8]
Hi!
You can make the condition downloading the file is not in the stream?

**Comment by smanikandan14** [comment]
Hi, Can you elaborate bit more on the issue ?

**Comment by crysan** [comment]
I'll try. 
Now download files are in the stream (analog AsyncTask). You can make this option to download not use threads?

**Comment by smanikandan14** [comment]
You mean to download synchronously on whatever thread it is called ?

**Comment by crysan** [comment]
Yes

**Comment by smanikandan14** [comment]
As you know its not advised to download or perform network operation on main thread. You would need a background thread to perform network operations. Which is what this library does. Takes care of that for you. I don't see why you need to do download synchronous operation on main thread. Even if you call this download operation on background thread and wanted synchronous behaviour, you can use call backs to hold on and perform  your synchronous operations.

**Comment by crysan** [comment]
Example: 
I have a main thread in which I am downloading files in a loop. When downloading each file should I check it successfully loaded or not. Depending on this, I need to update the program interface. 
Now this is not possible, because the main thread does not wait for the boot files.

**Comment by smanikandan14** [comment]
You can use DownloadStatusListener to know when files are downloaded. And defer the code you wanted to perform when all the files are downloaded. In between time make the main thread to idle (doesn't execute any code).

**Comment by crysan** [comment]
All right. I'll try. Thank you!
