### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by wenyang9319** [smanikandan14/ThinDownloadManager#84]
I was testing ThinDownloadManager with a bad internet connection situation, and the following error prompts out:

>  W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
 W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
 W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
 W/System.err:     at com.android.okio.Okio$2.read(Okio.java:116)
 W/System.err:     at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:150)
 W/System.err:     at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:97)
 W/System.err:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:202)
 W/System.err:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
 W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
 W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
 W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
 W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:136)
 W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:84)

Anyway to handle this? I was pass in the RetryPolicy but it didn't catch this error.
Further, onDownloadFailed from DownloadStatusListenerV1 didn't trigger.

**Comment by wenyang9319** [comment]
@smanikandan14  
Any thoughts would be appreciate =)

**Comment by wangzhengyi** [comment]
DownloadDispatcher already catch SocketTimeOutException, and use e.printStackTrace(); tell user this exception. so it is not error, it just a log for this exception.

**Comment by smanikandan14** [comment]
Agreed with @wangzhengyi . Closing this as not an issue.
