### ISSUE TITLE
Second request for same Dispatcher will never be redirect

### ISSUE THREAD

**Issue by wangzhengyi** [smanikandan14/ThinDownloadManager#86]
If first request need redirect, when redirect successed, it will set shouldAllowRedirects=false. but is second request also need redirect, shouldAllowRedirects do not initialize with true, it will never be able to redirect.

I create PR for this problem. link: https://github.com/smanikandan14/ThinDownloadManager/pull/85

**Comment by smanikandan14** [comment]
Merged the PR.
