### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wangzhengyi** [smanikandan14/ThinDownloadManager#87]
In DownloadDispatcher.java, mRequest is a global variable. if mRequest set DownloadStatusListenerV1 and DownloadStatusListenerV1 contains Activity instance, this will lead to memory leak. Because gc will not collect mRequest if there is no new request for this Dispatcher.
If @smanikandan14 you also think this is a problem, i will create pr for this issue.

I create pr for this issus, link:https://github.com/smanikandan14/ThinDownloadManager/pull/88

**Comment by smanikandan14** [comment]
PR Merged. Closing.
